"""create writing_model

Revision ID: 00793340fe98
Revises: add_should_end_roleplay
Create Date: 2026-02-17 11:39:41.259136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00793340fe98'
down_revision = 'add_should_end_roleplay'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
