"""add_completed_to_lesson

Revision ID: 19d03c7b9c9e
Revises: 495c214d7525
Create Date: 2026-02-01 13:32:27.639702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d03c7b9c9e'
down_revision = '495c214d7525'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('lesson', sa.Column('completed', sa.Boolean(), nullable=False, server_default=sa.text('false')))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'completed')
    # ### end Alembic commands ###
