"""added lesson

Revision ID: 19e267f284ba
Revises: fe34e0186203
Create Date: 2026-01-20 18:48:57.888687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e267f284ba'
down_revision = 'fe34e0186203'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
