"""user profile added

Revision ID: 1c989c448ea4
Revises: 002_add_email_verified
Create Date: 2026-01-17 18:07:20.323168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c989c448ea4'
down_revision = '002_add_email_verified'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
