"""user profile added

Revision ID: 29ee8e8986fe
Revises: 1c989c448ea4
Create Date: 2026-01-17 18:13:57.353737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ee8e8986fe'
down_revision = '1c989c448ea4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
