"""changed lesson table

Revision ID: 39d88faa3886
Revises: cbfd3b490661
Create Date: 2026-01-30 23:59:18.890144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39d88faa3886'
down_revision = 'cbfd3b490661'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('title', sa.String(), nullable=False))
    op.add_column('lesson', sa.Column('paragraphs', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_column('lesson', 'article')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('article', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('lesson', 'paragraphs')
    op.drop_column('lesson', 'title')
    # ### end Alembic commands ###
