"""a

Revision ID: 413d4035f910
Revises: 56fea8dbe7bd
Create Date: 2026-02-03 12:14:27.385060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413d4035f910'
down_revision = '56fea8dbe7bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roleplay', sa.Column('user_role', sa.String(), nullable=False))
    op.add_column('roleplay', sa.Column('ai_role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roleplay', 'ai_role')
    op.drop_column('roleplay', 'user_role')
    # ### end Alembic commands ###
