"""create writing_model

Revision ID: 482f1a83ef70
Revises: 00793340fe98
Create Date: 2026-02-17 11:42:04.256936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482f1a83ef70'
down_revision = '00793340fe98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
