"""add_progress_to_lesson

Revision ID: 495c214d7525
Revises: 39d88faa3886
Create Date: 2026-02-01 13:01:54.499059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '495c214d7525'
down_revision = '39d88faa3886'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'progress')
    # ### end Alembic commands ###
