"""create writing

Revision ID: 931c817c2bec
Revises: af03dab7230c
Create Date: 2026-02-17 11:53:33.122084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931c817c2bec'
down_revision = 'af03dab7230c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('writing_model', 'user_input',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('writing_model', 'user_input',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
