"""create writing

Revision ID: a98fd7b121b6
Revises: 482f1a83ef70
Create Date: 2026-02-17 11:45:52.041416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98fd7b121b6'
down_revision = '482f1a83ef70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
