"""add_grammar_to_lesson

Revision ID: c1625118e47b
Revises: 19d03c7b9c9e
Create Date: 2026-02-01 22:47:37.946471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1625118e47b'
down_revision = '19d03c7b9c9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('grammar', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'grammar')
    # ### end Alembic commands ###
