"""create writing

Revision ID: c3adba13e827
Revises: a98fd7b121b6
Create Date: 2026-02-17 11:49:06.246925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3adba13e827'
down_revision = 'a98fd7b121b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
