"""changed lesson table

Revision ID: cbfd3b490661
Revises: 0968cb4d0127
Create Date: 2026-01-30 23:49:12.480374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbfd3b490661'
down_revision = '0968cb4d0127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('vocab', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('lesson', sa.Column('article', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('lesson', sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('lesson', sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lesson', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('lesson', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('lesson', sa.Column('focus_areas', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('lesson', sa.Column('per_question', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('lesson', 'paragraphs')
    op.drop_column('lesson', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lesson', sa.Column('paragraphs', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('lesson', 'per_question')
    op.drop_column('lesson', 'focus_areas')
    op.drop_column('lesson', 'summary')
    op.drop_column('lesson', 'score')
    op.drop_column('lesson', 'answers')
    op.drop_column('lesson', 'questions')
    op.drop_column('lesson', 'article')
    op.drop_column('lesson', 'vocab')
    # ### end Alembic commands ###
